taskninja/calendars/routes.py
from datetime import datetime
from flask import redirect, render_template, url_for, Blueprint
from flask_login import current_user, login_required
from taskninja import db
from taskninja.calendars.utils import UserCalendar
from taskninja.users.forms import TaskForm
from taskninja.models import Task


calendars = Blueprint('calendars', __name__)


@calendars.route("/calendars/", defaults={'year': datetime.now().year, 'month': datetime.now().month, 'offset': 0})
@calendars.route("/calendars/<int:year>/<int:month>/<int:offset>", methods=['GET', 'POST'])
@login_required
def calendar(year, month, offset):
    time = datetime.now()
    today = f"{time.month}{time.day}"
    if offset == 2:
        month = month - 1
    else:
        month = month + offset
    if month == 13:
        month = 1
        year = year + 1
    if month == 0:
        month = 12
        year = year - 1
    cal = UserCalendar().formatmonth(theyear=year, themonth=month)
    return render_template('calendar.html', year=year, month=month, title='Calendar', cal=cal, today=today)


@calendars.route("/date/<string:month>/<string:day>/<string:year>", methods=['GET', 'POST'])
@login_required
def date(month, day, year):
    task_form = TaskForm()
    month = int(month)
    day = int(day)
    year = int(year)
    date = datetime(year=year, month=month, day=day)
    if task_form.validate_on_submit():
        task = Task(task=task_form.task.data, user_id=current_user.id, date_scheduled=datetime(year=datetime.now().year, month=month, day=day))
        db.session.add(task)
        db.session.commit()
        return redirect(url_for('calendars.date', month=month, day=day, year=year))
    return render_template('date.html', month=month, day=day, task_form=task_form, date=date)

taskninja/main/routes.py
from datetime import datetime
from flask import render_template, Blueprint

main = Blueprint('main', __name__)

@main.route("/")
def home():
    time = datetime.now()
    return render_template('index.html', time=time)

taskninja/users/routes.py
import requests
from datetime import datetime
from flask import flash, redirect, render_template, request, url_for, Blueprint
from flask_login import current_user, login_required, login_user, logout_user
from taskninja import bcrypt, db
from taskninja.users.forms import GoalForm, LoginForm, RegistrationForm, TaskForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from taskninja.models import Goal, Task, Users, Quote
from taskninja.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)




@users.route("/dashboard", methods=['GET', 'POST'])
@login_required
def dashboard():
    time = datetime.now()
    task_form = TaskForm()
    goal_form = GoalForm()
    if task_form.validate_on_submit():
        task = Task(task=task_form.task.data, user_id=current_user.id)
        db.session.add(task)
        db.session.commit()
        return redirect(url_for('users.dashboard'))
    if goal_form.validate_on_submit():
        goal = Goal(goal=goal_form.goal.data, user_id=current_user.id)
        db.session.add(goal)
        db.session.commit()
        return redirect(url_for('users.dashboard'))
    quote = Quote.query.first()
    if (quote is None) or (quote.time.day != datetime.utcnow().day):
        db.session.query(Quote).delete()
        db.session.commit()
        response = requests.get(url="https://zenquotes.io/api/today")
        response.raise_for_status()
        data = response.json()
        print("request sent")
        quote_text = data[0]['q']
        quote_author = data[0]['a']
        new_quote = Quote(quote=quote_text, author=quote_author)
        db.session.add(new_quote)
        db.session.commit()
        quote = Quote.query.first()
    return render_template("dashboard.html", task_form=task_form, goal_form=goal_form, quote=quote, time=time)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('users.dashboard'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = Users(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! you are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.dashboard'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'error')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='img/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/<int:id>/<type>/delete")
@login_required
def delete(id, type):
    if type == 'goal':
        Goal.query.filter_by(id=id).delete()
        db.session.commit()
    elif type == 'task':
        Task.query.filter_by(id=id).delete()
        db.session.commit()
    # Redirect to previous page
    return redirect(request.referrer)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('users.dashboard'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.dashboard'))
    user = Users.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

taskninja/templates/account.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section account-content">

    <form method="POST" action="" enctype="multipart/form-data">

        {{ form.hidden_tag() }}
        <fieldset class="form-main">
            <div class="media">
                <img class="rounded-circle account-img" src="{{ image_file }}">
                <div class="media-body">
                    <h2 class="account-heading">{{ current_user.username }}</h2>
                    <p class="secondary">{{ current_user.email }}</p>
                </div>
            </div>
            <div class="account-info">
                <legend>Account Info</legend>
            </div>

            <div class="form-item">
                {{ form.username.label(class="form-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-input is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-input", placeholder="Enter your username", autocomplete="off") }}
                {% endif %}
            </div>
            <div class="form-item">
                {{ form.email.label(class="form-label") }}

                {% if form.email.errors %}
                {{ form.email(class="form-input is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-input", placeholder="Enter your Email", autocomplete="off") }}
                {% endif %}
            </div>
            <div class="form-item">
                {{ form.picture.label(class="form-label") }}
                {{ form.picture(class="") }}
                {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <br><span class="invalid-feedback">{{ error }}</span>
                {% endfor %}
                {% endif %}
            </div>
            <div class="submit-button">
                {{ form.submit(class="btn sign-up-button") }}
            </div>
        </fieldset>
    </form>

</div>


{% endblock content %}

taskninja/templates/calendar.html
{% extends "layout.html" %}

{% block head %}

<style>
    td.d-{{ today }} {
    background-color: #f1f3f5;
    }
</style>

{% endblock head %}

{% block content %}


    <div class="cal-nav">
        <form class="left-cal-btn" action="{{ url_for('calendars.calendar', year=year, month=month, offset=2) }}"><button><ion-icon name="caret-back-outline"></ion-icon></button></form>
        <form class="left-cal-btn" action="{{ url_for('calendars.calendar') }}"><button>Today</button></form>
        <form class="right-cal-btn" action="{{ url_for('calendars.calendar', year=year, month=month, offset=1) }}"><button><ion-icon name="caret-forward-outline"></ion-icon></button></form>
    </div>


    {{ cal|safe }}



{% endblock content %}

taskninja/templates/dashboard.html
{% extends "layout.html" %}
{% block content %}

<div class="date">
    <h1>{{ time.strftime("%A, %B %-d %Y") }}</h1>
</div>

<section class="todo-section">
    <div class="todo-div">
        <h2>to-do list</h2>
        <div class="todo-table">
            <table class="table-test">
                <!--      PRINT OUT TASKS-->
                {% for task in current_user.tasks %}
                    {% if (task.date_scheduled.month, task.date_scheduled.day) == (time.month, time.day) %}
                        <tr>
                            <td class="todo-item">
                                {{ task.task }}
                                <form action="{{ url_for('users.delete', id=task.id, type='task') }}">
                                    <button class="complete-button">&radic;</button>
<!--                                    <button class="delete-btn">-</button>-->
                                </form>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                <!--      ADD NEW TASK -->

            </table>
            <form method="POST" action="" class="form add-task">
                {{ task_form.hidden_tag() }}
                <fieldset class="todo-input-form">
                    <div class="form-group">
                        {{ task_form.task(class="todo-input", autocomplete="off") }}
                    </div>
                </fieldset>
                <div>
                    {{ task_form.submit(class="add-button") }}
                </div>
            </form>
        </div>
    </div>
</section>


<section class="motivation-section">
    <div class="motivation-div">
        <h2>Quote of the Day</h2>
        <div class="motivation-table">
            <table>
                <tr>
                    <td class="motivation-item">
                        "{{ quote.quote }}"
                        <br/>
                        -{{ quote.author }}
                    </td>
                </tr>
            </table>
        </div>
    </div>
</section>

<section class="goals-section">
    <h2>{{ time.strftime('%B') }} Goals</h2>
    <div class="goal-table">
        <table>
            {% for goal in current_user.goals %}
                {% if goal.date_created.month == time.month %}
                <tr>
                    <td class="goal-item">
                        {{ goal.goal }}
                        <form action="{{ url_for('users.delete', id=goal.id, type='goal') }}">
                            <button class="complete-button">&radic;</button>
                        </form>
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </table>
        <form method="POST" action="" class="form add-goal">
            {{ goal_form.hidden_tag() }}
            <fieldset class="goal-input-form">
                <div class="form-group">
                    {{ goal_form.goal(class="goal-input", autocomplete="off") }}
                </div>
            </fieldset>
            <div class="add-goal-btn">
                {{ goal_form.submit(class="add-button") }}
            </div>
        </form>
    </div>
</section>


{% endblock content %}

taskninja/templates/date.html
{% extends "layout.html" %}
{% block content %}

    <div class="cal-nav">
        <form class="left-cal-btn" action="{{ url_for('calendars.calendar', year=date.year, month=date.month, offset=0) }}"><button><ion-icon name="arrow-undo"></ion-icon></button></form>
    </div>

    <h2 class="date-title">{{ date.strftime("%A, %B %-d %Y") }}</h2>


        <div class="date-div">
            <h2>to-do list</h2>
            <div class="todo-table">
                <table class="table-test">
                    <!--      PRINT OUT TASKS-->
                    {% for task in current_user.tasks %}
                        {% if (task.date_scheduled.month, task.date_scheduled.day) == (month, day) %}
                        <tr>
                            <td class="todo-item">
                                {{ task.task }}
                                <form action="{{ url_for('users.delete', id=task.id, type='task') }}">
                                    <button class="complete-button">&radic;</button>
                                </form>
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                    <!--      ADD NEW TASK -->

                </table>
                <form method="POST" action="" class="form add-task">
                    {{ task_form.hidden_tag() }}
                    <fieldset class="todo-input-form">
                        <div class="form-group">
                            {{ task_form.task(class="todo-input", autocomplete="off") }}
                        </div>
                    </fieldset>
                    <div>
                        {{ task_form.submit(class="add-button") }}
                    </div>
                </form>
            </div>
        </div>



{% endblock content %}

taskninja/templates/index.html
{% extends "layout.html" %}
{% block content %}
<img
        class="splash-img"
        src="../static/img/splash.jpeg"
        alt="Photo by Guilain Demoutiers on Unsplash"
/>

<div class="pitch">
    <p>
        Are you tired of constantly forgetting what you need to do and when
        you need to do it? Look no further, because Task Ninja is here to
        revolutionize the way you manage your to-do list. Our to-do list
        application is designed to make your life easier and more organized.
        With a user-friendly interface, you can quickly and easily add tasks
        or schedule them for a future date. <br/><br/>So why wait? Say goodbye to cluttered
        and disorganized lists, and say hello to Task Ninja. Start getting
        things done and make the most out of your day!
    </p>
    <a class="cta register-button" href="{{ url_for('users.register') }}">
        <button id="register">Register Now  <ion-icon class="arrow" name="arrow-forward-outline"></ion-icon></button>
    </a>
</div>

{% endblock content %}

taskninja/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link
            href="https://fonts.googleapis.com/css2?family=Dosis:wght@300&family=Inter:wght@400;500;700&family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Ubuntu:wght@300;400;500;700&display=swap"
            rel="stylesheet"
    />
    <link type="text/css" href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet"/>

<!--    ref="../static/css/styles.css" -->
    {% block head %}
    {% endblock head %}

    {% if title %}
    <title>Task Ninja: {{ title }}</title>
    {% else %}
    <title>Task Ninja</title>
    {% endif %}
</head>
<body>
<header>
    <a href="{{ url_for('main.home') }}" class="logo">Task Ninja</a>
    <!--        NAVIGATION-->
    <nav class="nav-bar">
        <ul class="nav__links" links>
            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('users.dashboard') }}">Dashboard</a></li>
            <li><a href="{{ url_for('calendars.calendar') }}">Calendar</a></li>
            <li><a href="{{ url_for('users.account') }}">Account</a></li>
            <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
            {% else %}
            <li><a href="{{ url_for('users.login') }}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
    {% if not current_user.is_authenticated %}

    {% endif %}
</header>
<div class="container">


    <!-- UNCOMMENT BELOW ONCE DONE -->

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    {% block content %}

    {% endblock content %}

    <!-- UNCOMMENT ABOVE ONCE DONE -->
    <footer>&copy; Charles Leighton 2023</footer>
</div>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>

taskninja/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="login-form">
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-main">
                <div class="log-in">
                    <legend class="border-bottom mb-4">Log In</legend>
                </div>

                <div class="form-item">
                    {{ form.email.label(class="form-label") }}

                    {% if form.email.errors %}
                    {{ form.email(class="form-input is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-input", placeholder="Enter your Email", autocomplete="off") }}
                    {% endif %}
                </div>
                <div class="form-item">
                    {{ form.password.label(class="form-label") }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-input is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class="form-input", placeholder="Enter your Password", autocomplete="off") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
                <div class="submit-button">
                    {{ form.submit(class="btn sign-up-button") }}
                </div>
                <div class="login-small">
                    <small class="forgot-password">
                        <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                    </small>
                </div>
                <div class="login-small">
                    <small class="text-muted">
                        Need An Account? <a class="small-sign-up" href="{{ url_for('users.register') }}">Sign Up Now</a>
                    </small>
                </div>
            </fieldset>

        </form>
    </div>

</div>
{% endblock content %}

taskninja/templates/register.html
{% extends "layout.html" %}

{% block head %}

{% endblock head %}

{% block content %}
<div class="login-form">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-main">
            <div class="join-today">
                <legend>Join Today</legend>
            </div>

            <div class="form-item">
                {{ form.username.label(class="form-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-input is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-input", placeholder="Enter your username", autocomplete="off") }}
                {% endif %}
            </div>
            <div class="form-item">
                {{ form.email.label(class="form-label") }}

                {% if form.email.errors %}
                {{ form.email(class="form-input is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-input", placeholder="Enter your Email", autocomplete="off") }}
                {% endif %}
            </div>
            <div class="form-item">
                {{ form.password.label(class="form-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-input is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-input", placeholder="Enter your Password", autocomplete="off") }}
                {% endif %}
            </div>
            <div class="form-item">
                {{ form.confirm_password.label(class="form-label") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-input is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-input", placeholder="Confirm your Password", autocomplete="off") }}
                {% endif %}
            </div>

            <div class="submit-button">
                {{ form.submit(class="btn sign-up-button") }}
            </div>
            <div class="account-small">
                <small class="text-muted">
                    Already Have An Account? <a class="small-sign-in" href="{{ url_for('users.login') }}">Sign In</a>
                </small>
            </div>
        </fieldset>
    </form>
</div>

{% endblock content %}

taskninja/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
<div class="login-form">
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-main">
                <div class="log-in">
                    <legend class="border-bottom mb-4">Reset Password</legend>
                </div>

                <div class="form-item">
                    {{ form.email.label(class="form-label") }}

                    {% if form.email.errors %}
                    {{ form.email(class="form-input is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-input", placeholder="Enter your Email", autocomplete="off") }}
                    {% endif %}
                </div>
                <div class="submit-button">
                    {{ form.submit(class="btn sign-up-button") }}
                </div>
            </fieldset>

        </form>
    </div>

</div>
{% endblock content %}

taskninja/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
<div class="login-form">
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-main">
                <div class="log-in">
                    <legend class="border-bottom mb-4">Reset Password</legend>
                </div>
                <div class="form-item">
                    {{ form.password.label(class="form-label") }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-input is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class="form-input", placeholder="Enter your Password", autocomplete="off") }}
                    {% endif %}
                </div>
                <div class="form-item">
                    {{ form.confirm_password.label(class="form-label") }}
                    {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-input is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.confirm_password(class="form-input", placeholder="Confirm Password", autocomplete="off") }}
                    {% endif %}
                </div>
                <div class="submit-button">
                    {{ form.submit(class="btn sign-up-button") }}
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock content %}